/**
 * ExpressSoap.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.paymentgateway.elementexpress.transaction;

public interface ExpressSoap extends java.rmi.Remote {
    public com.paymentgateway.elementexpress.transaction.Response healthCheck(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response timeCheck(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response accountTokenCreate(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response accountTokenActivate(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response magneprintDataDecrypt(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response transactionSetup(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.TransactionSetup transactionSetup, com.paymentgateway.elementexpress.transaction.Address address, com.paymentgateway.elementexpress.transaction.PaymentAccount paymentAccount, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response BINQuery(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response enhancedBINQuery(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response transactionSetupExpire(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.TransactionSetup transactionSetup, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response creditCardSale(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.Address address, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response creditCardAuthorization(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.Address address, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response creditCardAuthorizationCompletion(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response creditCardForce(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response creditCardCredit(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response creditCardAdjustment(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response creditCardReversal(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response creditCardIncrementalAuthorization(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response creditCardBalanceInquiry(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response creditCardVoid(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response creditCardAVSOnly(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.Address address, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response creditCardReturn(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response debitCardSale(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response debitCardReturn(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response debitCardReversal(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response debitCardPinlessSale(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response debitCardPinlessReturn(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response batchClose(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Batch batch, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response batchItemQuery(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Batch batch, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response batchTotalsQuery(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Batch batch, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response checkSale(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.DemandDepositAccount demandDepositAccount, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.Identification identification, com.paymentgateway.elementexpress.transaction.Address address, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response checkCredit(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.DemandDepositAccount demandDepositAccount, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.Identification identification, com.paymentgateway.elementexpress.transaction.Address address, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response checkVerification(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.DemandDepositAccount demandDepositAccount, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.Identification identification, com.paymentgateway.elementexpress.transaction.Address address, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response checkReturn(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response checkVoid(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response checkReversal(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response EBTSale(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.EBT ebt, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response EBTCredit(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.EBT ebt, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response EBTVoucher(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.EBT ebt, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response EBTBalanceInquiry(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.EBT ebt, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response EBTReversal(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.EBT ebt, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response giftCardSystemCheck(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response giftCardActivate(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response giftCardSale(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response giftCardReload(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response giftCardCredit(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response giftCardReturn(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response giftCardBalanceInquiry(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response giftCardUnload(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response giftCardClose(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response giftCardAuthorization(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response giftCardAuthorizationCompletion(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response giftCardReversal(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response giftCardReport(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.transaction.Response giftCardBalanceTransfer(com.paymentgateway.elementexpress.transaction.Credentials credentials, com.paymentgateway.elementexpress.transaction.Application application, com.paymentgateway.elementexpress.transaction.Terminal terminal, com.paymentgateway.elementexpress.transaction.Card card, com.paymentgateway.elementexpress.transaction.Transaction transaction, com.paymentgateway.elementexpress.transaction.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
}
