/**
 * ExpressSoap.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.paymentgateway.elementexpress.services;

public interface ExpressSoap extends java.rmi.Remote {
    public com.paymentgateway.elementexpress.services.Response paymentAccountCreateWithTransID(com.paymentgateway.elementexpress.services.Credentials credentials, com.paymentgateway.elementexpress.services.Application application, com.paymentgateway.elementexpress.services.Transaction transaction, com.paymentgateway.elementexpress.services.PaymentAccount paymentAccount, com.paymentgateway.elementexpress.services.Address address, com.paymentgateway.elementexpress.services.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.services.Response paymentAccountCreate(com.paymentgateway.elementexpress.services.Credentials credentials, com.paymentgateway.elementexpress.services.Application application, com.paymentgateway.elementexpress.services.PaymentAccount paymentAccount, com.paymentgateway.elementexpress.services.Card card, com.paymentgateway.elementexpress.services.DemandDepositAccount demandDepositAccount, com.paymentgateway.elementexpress.services.Address address, com.paymentgateway.elementexpress.services.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.services.TokenCreateResponse tokenCreate(com.paymentgateway.elementexpress.services.Credentials credentials, com.paymentgateway.elementexpress.services.Application application, com.paymentgateway.elementexpress.services.Terminal terminal, com.paymentgateway.elementexpress.services.Card card, com.paymentgateway.elementexpress.services.Token token, com.paymentgateway.elementexpress.services.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.services.TokenCreateResponse tokenCreateWithTransID(com.paymentgateway.elementexpress.services.Credentials credentials, com.paymentgateway.elementexpress.services.Application application, com.paymentgateway.elementexpress.services.Terminal terminal, com.paymentgateway.elementexpress.services.Transaction transaction, com.paymentgateway.elementexpress.services.Token token, com.paymentgateway.elementexpress.services.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.services.Response paymentAccountUpdate(com.paymentgateway.elementexpress.services.Credentials credentials, com.paymentgateway.elementexpress.services.Application application, com.paymentgateway.elementexpress.services.PaymentAccount paymentAccount, com.paymentgateway.elementexpress.services.Card card, com.paymentgateway.elementexpress.services.DemandDepositAccount demandDepositAccount, com.paymentgateway.elementexpress.services.Address address, com.paymentgateway.elementexpress.services.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.services.Response paymentAccountDelete(com.paymentgateway.elementexpress.services.Credentials credentials, com.paymentgateway.elementexpress.services.Application application, com.paymentgateway.elementexpress.services.PaymentAccount paymentAccount, com.paymentgateway.elementexpress.services.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.services.Response paymentAccountQuery(com.paymentgateway.elementexpress.services.Credentials credentials, com.paymentgateway.elementexpress.services.Application application, com.paymentgateway.elementexpress.services.PaymentAccountParameters paymentAccountParameters, com.paymentgateway.elementexpress.services.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.services.Response paymentAccountQueryRecordCount(com.paymentgateway.elementexpress.services.Credentials credentials, com.paymentgateway.elementexpress.services.Application application, com.paymentgateway.elementexpress.services.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.services.Response paymentAccountQueryTokenReport(com.paymentgateway.elementexpress.services.Credentials credentials, com.paymentgateway.elementexpress.services.Application application, com.paymentgateway.elementexpress.services.Paging paging, com.paymentgateway.elementexpress.services.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.services.Response paymentAccountAutoUpdate(com.paymentgateway.elementexpress.services.Credentials credentials, com.paymentgateway.elementexpress.services.Application application, com.paymentgateway.elementexpress.services.PaymentAccount paymentAccount, com.paymentgateway.elementexpress.services.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.services.Response scheduledTaskDelete(com.paymentgateway.elementexpress.services.Credentials credentials, com.paymentgateway.elementexpress.services.Application application, com.paymentgateway.elementexpress.services.ScheduledTask scheduledTask, com.paymentgateway.elementexpress.services.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.services.Response scheduledTaskQuery(com.paymentgateway.elementexpress.services.Credentials credentials, com.paymentgateway.elementexpress.services.Application application, com.paymentgateway.elementexpress.services.ScheduledTaskParameters scheduledTaskParameters, com.paymentgateway.elementexpress.services.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.services.Response scheduledTaskUpdate(com.paymentgateway.elementexpress.services.Credentials credentials, com.paymentgateway.elementexpress.services.Application application, com.paymentgateway.elementexpress.services.ScheduledTask scheduledTask, com.paymentgateway.elementexpress.services.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
    public com.paymentgateway.elementexpress.services.Response scheduledTaskRetry(com.paymentgateway.elementexpress.services.Credentials credentials, com.paymentgateway.elementexpress.services.Application application, com.paymentgateway.elementexpress.services.ScheduledTask scheduledTask, com.paymentgateway.elementexpress.services.ExtendedParameters[] extendedParameters) throws java.rmi.RemoteException;
}
