//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 10:13:20 AM EDT 
//


package com.unilog.punchout.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SupplierPartID"/>
 *         &lt;element ref="{}SupplierPartAuxiliaryID" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "supplierPartID",
    "supplierPartAuxiliaryID"
})
@XmlRootElement(name = "ItemID")
public class ItemID
    implements Serializable, Equals, HashCode, ToString
{

    @XmlElement(name = "SupplierPartID", required = true)
    protected SupplierPartID supplierPartID;
    @XmlElement(name = "SupplierPartAuxiliaryID")
    protected SupplierPartAuxiliaryID supplierPartAuxiliaryID;
   
    /**
     * Gets the value of the supplierPartID property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierPartID }
     *     
     */
    public SupplierPartID getSupplierPartID() {
        return supplierPartID;
    }

    /**
     * Sets the value of the supplierPartID property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierPartID }
     *     
     */
    public void setSupplierPartID(SupplierPartID value) {
        this.supplierPartID = value;
    }

    /**
     * Gets the value of the supplierPartAuxiliaryID property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierPartAuxiliaryID }
     *     
     */
    public SupplierPartAuxiliaryID getSupplierPartAuxiliaryID() {
        return supplierPartAuxiliaryID;
    }

    /**
     * Sets the value of the supplierPartAuxiliaryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierPartAuxiliaryID }
     *     
     */
    public void setSupplierPartAuxiliaryID(SupplierPartAuxiliaryID value) {
        this.supplierPartAuxiliaryID = value;
    }
   
    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            SupplierPartID theSupplierPartID;
            theSupplierPartID = this.getSupplierPartID();
            strategy.appendField(locator, this, "supplierPartID", buffer, theSupplierPartID);
        }
        {
            SupplierPartAuxiliaryID theSupplierPartAuxiliaryID;
            theSupplierPartAuxiliaryID = this.getSupplierPartAuxiliaryID();
            strategy.appendField(locator, this, "supplierPartAuxiliaryID", buffer, theSupplierPartAuxiliaryID);
        }
       
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof ItemID)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ItemID that = ((ItemID) object);
        {
            SupplierPartID lhsSupplierPartID;
            lhsSupplierPartID = this.getSupplierPartID();
            SupplierPartID rhsSupplierPartID;
            rhsSupplierPartID = that.getSupplierPartID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "supplierPartID", lhsSupplierPartID), LocatorUtils.property(thatLocator, "supplierPartID", rhsSupplierPartID), lhsSupplierPartID, rhsSupplierPartID)) {
                return false;
            }
        }
        {
            SupplierPartAuxiliaryID lhsSupplierPartAuxiliaryID;
            lhsSupplierPartAuxiliaryID = this.getSupplierPartAuxiliaryID();
            SupplierPartAuxiliaryID rhsSupplierPartAuxiliaryID;
            rhsSupplierPartAuxiliaryID = that.getSupplierPartAuxiliaryID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "supplierPartAuxiliaryID", lhsSupplierPartAuxiliaryID), LocatorUtils.property(thatLocator, "supplierPartAuxiliaryID", rhsSupplierPartAuxiliaryID), lhsSupplierPartAuxiliaryID, rhsSupplierPartAuxiliaryID)) {
                return false;
            }
        }
        
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            SupplierPartID theSupplierPartID;
            theSupplierPartID = this.getSupplierPartID();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "supplierPartID", theSupplierPartID), currentHashCode, theSupplierPartID);
        }
        {
            SupplierPartAuxiliaryID theSupplierPartAuxiliaryID;
            theSupplierPartAuxiliaryID = this.getSupplierPartAuxiliaryID();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "supplierPartAuxiliaryID", theSupplierPartAuxiliaryID), currentHashCode, theSupplierPartAuxiliaryID);
        }
      
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
