//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 10:13:20 AM EDT 
//


package com.unilog.punchout.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}OrderTarget"/>
 *         &lt;element ref="{}OrderProtocol" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orderTarget",
    "orderProtocol"
})
@XmlRootElement(name = "OrderMethod")
public class OrderMethod
    implements Serializable, Equals, HashCode, ToString
{

    @XmlElement(name = "OrderTarget", required = true)
    protected OrderTarget orderTarget;
    @XmlElement(name = "OrderProtocol")
    protected OrderProtocol orderProtocol;

    /**
     * Gets the value of the orderTarget property.
     * 
     * @return
     *     possible object is
     *     {@link OrderTarget }
     *     
     */
    public OrderTarget getOrderTarget() {
        return orderTarget;
    }

    /**
     * Sets the value of the orderTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderTarget }
     *     
     */
    public void setOrderTarget(OrderTarget value) {
        this.orderTarget = value;
    }

    /**
     * Gets the value of the orderProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link OrderProtocol }
     *     
     */
    public OrderProtocol getOrderProtocol() {
        return orderProtocol;
    }

    /**
     * Sets the value of the orderProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderProtocol }
     *     
     */
    public void setOrderProtocol(OrderProtocol value) {
        this.orderProtocol = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            OrderTarget theOrderTarget;
            theOrderTarget = this.getOrderTarget();
            strategy.appendField(locator, this, "orderTarget", buffer, theOrderTarget);
        }
        {
            OrderProtocol theOrderProtocol;
            theOrderProtocol = this.getOrderProtocol();
            strategy.appendField(locator, this, "orderProtocol", buffer, theOrderProtocol);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof OrderMethod)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final OrderMethod that = ((OrderMethod) object);
        {
            OrderTarget lhsOrderTarget;
            lhsOrderTarget = this.getOrderTarget();
            OrderTarget rhsOrderTarget;
            rhsOrderTarget = that.getOrderTarget();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderTarget", lhsOrderTarget), LocatorUtils.property(thatLocator, "orderTarget", rhsOrderTarget), lhsOrderTarget, rhsOrderTarget)) {
                return false;
            }
        }
        {
            OrderProtocol lhsOrderProtocol;
            lhsOrderProtocol = this.getOrderProtocol();
            OrderProtocol rhsOrderProtocol;
            rhsOrderProtocol = that.getOrderProtocol();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderProtocol", lhsOrderProtocol), LocatorUtils.property(thatLocator, "orderProtocol", rhsOrderProtocol), lhsOrderProtocol, rhsOrderProtocol)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            OrderTarget theOrderTarget;
            theOrderTarget = this.getOrderTarget();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderTarget", theOrderTarget), currentHashCode, theOrderTarget);
        }
        {
            OrderProtocol theOrderProtocol;
            theOrderProtocol = this.getOrderProtocol();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderProtocol", theOrderProtocol), currentHashCode, theOrderProtocol);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
