//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 10:13:20 AM EDT 
//


package com.unilog.punchout.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}OriginatorCookie"/>
 *         &lt;element ref="{}ReturnData" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "originatorCookie",
    "returnData"
})
@XmlRootElement(name = "ProviderDoneMessage")
public class ProviderDoneMessage
    implements Serializable, Equals, HashCode, ToString
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 4837817395209583539L;
	@XmlElement(name = "OriginatorCookie", required = true)
    protected OriginatorCookie originatorCookie;
    @XmlElement(name = "ReturnData")
    protected List<ReturnData> returnData;

    /**
     * Gets the value of the originatorCookie property.
     * 
     * @return
     *     possible object is
     *     {@link OriginatorCookie }
     *     
     */
    public OriginatorCookie getOriginatorCookie() {
        return originatorCookie;
    }

    /**
     * Sets the value of the originatorCookie property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginatorCookie }
     *     
     */
    public void setOriginatorCookie(OriginatorCookie value) {
        this.originatorCookie = value;
    }

    /**
     * Gets the value of the returnData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the returnData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReturnData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReturnData }
     * 
     * 
     */
    public List<ReturnData> getReturnData() {
        if (returnData == null) {
            returnData = new ArrayList<ReturnData>();
        }
        return this.returnData;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            OriginatorCookie theOriginatorCookie;
            theOriginatorCookie = this.getOriginatorCookie();
            strategy.appendField(locator, this, "originatorCookie", buffer, theOriginatorCookie);
        }
        {
            List<ReturnData> theReturnData;
            theReturnData = (((this.returnData!= null)&&(!this.returnData.isEmpty()))?this.getReturnData():null);
            strategy.appendField(locator, this, "returnData", buffer, theReturnData);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof ProviderDoneMessage)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ProviderDoneMessage that = ((ProviderDoneMessage) object);
        {
            OriginatorCookie lhsOriginatorCookie;
            lhsOriginatorCookie = this.getOriginatorCookie();
            OriginatorCookie rhsOriginatorCookie;
            rhsOriginatorCookie = that.getOriginatorCookie();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "originatorCookie", lhsOriginatorCookie), LocatorUtils.property(thatLocator, "originatorCookie", rhsOriginatorCookie), lhsOriginatorCookie, rhsOriginatorCookie)) {
                return false;
            }
        }
        {
            List<ReturnData> lhsReturnData;
            lhsReturnData = (((this.returnData!= null)&&(!this.returnData.isEmpty()))?this.getReturnData():null);
            List<ReturnData> rhsReturnData;
            rhsReturnData = (((that.returnData!= null)&&(!that.returnData.isEmpty()))?that.getReturnData():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "returnData", lhsReturnData), LocatorUtils.property(thatLocator, "returnData", rhsReturnData), lhsReturnData, rhsReturnData)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            OriginatorCookie theOriginatorCookie;
            theOriginatorCookie = this.getOriginatorCookie();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "originatorCookie", theOriginatorCookie), currentHashCode, theOriginatorCookie);
        }
        {
            List<ReturnData> theReturnData;
            theReturnData = (((this.returnData!= null)&&(!this.returnData.isEmpty()))?this.getReturnData():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "returnData", theReturnData), currentHashCode, theReturnData);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
