//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 10:13:20 AM EDT 
//


package com.unilog.punchout.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{}ProfileRequest"/>
 *           &lt;element ref="{}OrderRequest"/>
 *           &lt;element ref="{}MasterAgreementRequest"/>
 *           &lt;element ref="{}PunchOutSetupRequest"/>
 *           &lt;element ref="{}ProviderSetupRequest"/>
 *           &lt;element ref="{}StatusUpdateRequest"/>
 *           &lt;element ref="{}GetPendingRequest"/>
 *           &lt;element ref="{}SubscriptionListRequest"/>
 *           &lt;element ref="{}SubscriptionContentRequest"/>
 *           &lt;element ref="{}SupplierListRequest"/>
 *           &lt;element ref="{}SupplierDataRequest"/>
 *           &lt;element ref="{}CopyRequest"/>
 *           &lt;element ref="{}CatalogUploadRequest"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="deploymentMode" default="production">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="test"/>
 *             &lt;enumeration value="production"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "profileRequest",
    "orderRequest",
    "masterAgreementRequest",
    "punchOutSetupRequest",
    "providerSetupRequest",
    "statusUpdateRequest",
    "getPendingRequest",
    "subscriptionListRequest",
    "subscriptionContentRequest",
    "supplierListRequest",
    "supplierDataRequest",
    "copyRequest",
    "catalogUploadRequest"
})
@XmlRootElement(name = "Request")
public class Request
    implements Serializable, Equals, HashCode, ToString
{

    @XmlElement(name = "ProfileRequest")
    protected ProfileRequest profileRequest;
    @XmlElement(name = "OrderRequest")
    protected OrderRequest orderRequest;
    @XmlElement(name = "MasterAgreementRequest")
    protected MasterAgreementRequest masterAgreementRequest;
    @XmlElement(name = "PunchOutSetupRequest")
    protected PunchOutSetupRequest punchOutSetupRequest;
    @XmlElement(name = "ProviderSetupRequest")
    protected ProviderSetupRequest providerSetupRequest;
    @XmlElement(name = "StatusUpdateRequest")
    protected StatusUpdateRequest statusUpdateRequest;
    @XmlElement(name = "GetPendingRequest")
    protected GetPendingRequest getPendingRequest;
    @XmlElement(name = "SubscriptionListRequest")
    protected SubscriptionListRequest subscriptionListRequest;
    @XmlElement(name = "SubscriptionContentRequest")
    protected SubscriptionContentRequest subscriptionContentRequest;
    @XmlElement(name = "SupplierListRequest")
    protected SupplierListRequest supplierListRequest;
    @XmlElement(name = "SupplierDataRequest")
    protected SupplierDataRequest supplierDataRequest;
    @XmlElement(name = "CopyRequest")
    protected CopyRequest copyRequest;
    @XmlElement(name = "CatalogUploadRequest")
    protected CatalogUploadRequest catalogUploadRequest;
    @XmlAttribute(name = "deploymentMode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String deploymentMode;

    /**
     * Gets the value of the profileRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ProfileRequest }
     *     
     */
    public ProfileRequest getProfileRequest() {
        return profileRequest;
    }

    /**
     * Sets the value of the profileRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProfileRequest }
     *     
     */
    public void setProfileRequest(ProfileRequest value) {
        this.profileRequest = value;
    }

    /**
     * Gets the value of the orderRequest property.
     * 
     * @return
     *     possible object is
     *     {@link OrderRequest }
     *     
     */
    public OrderRequest getOrderRequest() {
        return orderRequest;
    }

    /**
     * Sets the value of the orderRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderRequest }
     *     
     */
    public void setOrderRequest(OrderRequest value) {
        this.orderRequest = value;
    }

    /**
     * Gets the value of the masterAgreementRequest property.
     * 
     * @return
     *     possible object is
     *     {@link MasterAgreementRequest }
     *     
     */
    public MasterAgreementRequest getMasterAgreementRequest() {
        return masterAgreementRequest;
    }

    /**
     * Sets the value of the masterAgreementRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link MasterAgreementRequest }
     *     
     */
    public void setMasterAgreementRequest(MasterAgreementRequest value) {
        this.masterAgreementRequest = value;
    }

    /**
     * Gets the value of the punchOutSetupRequest property.
     * 
     * @return
     *     possible object is
     *     {@link PunchOutSetupRequest }
     *     
     */
    public PunchOutSetupRequest getPunchOutSetupRequest() {
        return punchOutSetupRequest;
    }

    /**
     * Sets the value of the punchOutSetupRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link PunchOutSetupRequest }
     *     
     */
    public void setPunchOutSetupRequest(PunchOutSetupRequest value) {
        this.punchOutSetupRequest = value;
    }

    /**
     * Gets the value of the providerSetupRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ProviderSetupRequest }
     *     
     */
    public ProviderSetupRequest getProviderSetupRequest() {
        return providerSetupRequest;
    }

    /**
     * Sets the value of the providerSetupRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProviderSetupRequest }
     *     
     */
    public void setProviderSetupRequest(ProviderSetupRequest value) {
        this.providerSetupRequest = value;
    }

    /**
     * Gets the value of the statusUpdateRequest property.
     * 
     * @return
     *     possible object is
     *     {@link StatusUpdateRequest }
     *     
     */
    public StatusUpdateRequest getStatusUpdateRequest() {
        return statusUpdateRequest;
    }

    /**
     * Sets the value of the statusUpdateRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusUpdateRequest }
     *     
     */
    public void setStatusUpdateRequest(StatusUpdateRequest value) {
        this.statusUpdateRequest = value;
    }

    /**
     * Gets the value of the getPendingRequest property.
     * 
     * @return
     *     possible object is
     *     {@link GetPendingRequest }
     *     
     */
    public GetPendingRequest getGetPendingRequest() {
        return getPendingRequest;
    }

    /**
     * Sets the value of the getPendingRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetPendingRequest }
     *     
     */
    public void setGetPendingRequest(GetPendingRequest value) {
        this.getPendingRequest = value;
    }

    /**
     * Gets the value of the subscriptionListRequest property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriptionListRequest }
     *     
     */
    public SubscriptionListRequest getSubscriptionListRequest() {
        return subscriptionListRequest;
    }

    /**
     * Sets the value of the subscriptionListRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriptionListRequest }
     *     
     */
    public void setSubscriptionListRequest(SubscriptionListRequest value) {
        this.subscriptionListRequest = value;
    }

    /**
     * Gets the value of the subscriptionContentRequest property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriptionContentRequest }
     *     
     */
    public SubscriptionContentRequest getSubscriptionContentRequest() {
        return subscriptionContentRequest;
    }

    /**
     * Sets the value of the subscriptionContentRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriptionContentRequest }
     *     
     */
    public void setSubscriptionContentRequest(SubscriptionContentRequest value) {
        this.subscriptionContentRequest = value;
    }

    /**
     * Gets the value of the supplierListRequest property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierListRequest }
     *     
     */
    public SupplierListRequest getSupplierListRequest() {
        return supplierListRequest;
    }

    /**
     * Sets the value of the supplierListRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierListRequest }
     *     
     */
    public void setSupplierListRequest(SupplierListRequest value) {
        this.supplierListRequest = value;
    }

    /**
     * Gets the value of the supplierDataRequest property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierDataRequest }
     *     
     */
    public SupplierDataRequest getSupplierDataRequest() {
        return supplierDataRequest;
    }

    /**
     * Sets the value of the supplierDataRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierDataRequest }
     *     
     */
    public void setSupplierDataRequest(SupplierDataRequest value) {
        this.supplierDataRequest = value;
    }

    /**
     * Gets the value of the copyRequest property.
     * 
     * @return
     *     possible object is
     *     {@link CopyRequest }
     *     
     */
    public CopyRequest getCopyRequest() {
        return copyRequest;
    }

    /**
     * Sets the value of the copyRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link CopyRequest }
     *     
     */
    public void setCopyRequest(CopyRequest value) {
        this.copyRequest = value;
    }

    /**
     * Gets the value of the catalogUploadRequest property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogUploadRequest }
     *     
     */
    public CatalogUploadRequest getCatalogUploadRequest() {
        return catalogUploadRequest;
    }

    /**
     * Sets the value of the catalogUploadRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogUploadRequest }
     *     
     */
    public void setCatalogUploadRequest(CatalogUploadRequest value) {
        this.catalogUploadRequest = value;
    }

    /**
     * Gets the value of the deploymentMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeploymentMode() {
        if (deploymentMode == null) {
            return "production";
        } else {
            return deploymentMode;
        }
    }

    /**
     * Sets the value of the deploymentMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeploymentMode(String value) {
        this.deploymentMode = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            ProfileRequest theProfileRequest;
            theProfileRequest = this.getProfileRequest();
            strategy.appendField(locator, this, "profileRequest", buffer, theProfileRequest);
        }
        {
            OrderRequest theOrderRequest;
            theOrderRequest = this.getOrderRequest();
            strategy.appendField(locator, this, "orderRequest", buffer, theOrderRequest);
        }
        {
            MasterAgreementRequest theMasterAgreementRequest;
            theMasterAgreementRequest = this.getMasterAgreementRequest();
            strategy.appendField(locator, this, "masterAgreementRequest", buffer, theMasterAgreementRequest);
        }
        {
            PunchOutSetupRequest thePunchOutSetupRequest;
            thePunchOutSetupRequest = this.getPunchOutSetupRequest();
            strategy.appendField(locator, this, "punchOutSetupRequest", buffer, thePunchOutSetupRequest);
        }
        {
            ProviderSetupRequest theProviderSetupRequest;
            theProviderSetupRequest = this.getProviderSetupRequest();
            strategy.appendField(locator, this, "providerSetupRequest", buffer, theProviderSetupRequest);
        }
        {
            StatusUpdateRequest theStatusUpdateRequest;
            theStatusUpdateRequest = this.getStatusUpdateRequest();
            strategy.appendField(locator, this, "statusUpdateRequest", buffer, theStatusUpdateRequest);
        }
        {
            GetPendingRequest theGetPendingRequest;
            theGetPendingRequest = this.getGetPendingRequest();
            strategy.appendField(locator, this, "getPendingRequest", buffer, theGetPendingRequest);
        }
        {
            SubscriptionListRequest theSubscriptionListRequest;
            theSubscriptionListRequest = this.getSubscriptionListRequest();
            strategy.appendField(locator, this, "subscriptionListRequest", buffer, theSubscriptionListRequest);
        }
        {
            SubscriptionContentRequest theSubscriptionContentRequest;
            theSubscriptionContentRequest = this.getSubscriptionContentRequest();
            strategy.appendField(locator, this, "subscriptionContentRequest", buffer, theSubscriptionContentRequest);
        }
        {
            SupplierListRequest theSupplierListRequest;
            theSupplierListRequest = this.getSupplierListRequest();
            strategy.appendField(locator, this, "supplierListRequest", buffer, theSupplierListRequest);
        }
        {
            SupplierDataRequest theSupplierDataRequest;
            theSupplierDataRequest = this.getSupplierDataRequest();
            strategy.appendField(locator, this, "supplierDataRequest", buffer, theSupplierDataRequest);
        }
        {
            CopyRequest theCopyRequest;
            theCopyRequest = this.getCopyRequest();
            strategy.appendField(locator, this, "copyRequest", buffer, theCopyRequest);
        }
        {
            CatalogUploadRequest theCatalogUploadRequest;
            theCatalogUploadRequest = this.getCatalogUploadRequest();
            strategy.appendField(locator, this, "catalogUploadRequest", buffer, theCatalogUploadRequest);
        }
        {
            String theDeploymentMode;
            theDeploymentMode = this.getDeploymentMode();
            strategy.appendField(locator, this, "deploymentMode", buffer, theDeploymentMode);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Request)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Request that = ((Request) object);
        {
            ProfileRequest lhsProfileRequest;
            lhsProfileRequest = this.getProfileRequest();
            ProfileRequest rhsProfileRequest;
            rhsProfileRequest = that.getProfileRequest();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "profileRequest", lhsProfileRequest), LocatorUtils.property(thatLocator, "profileRequest", rhsProfileRequest), lhsProfileRequest, rhsProfileRequest)) {
                return false;
            }
        }
        {
            OrderRequest lhsOrderRequest;
            lhsOrderRequest = this.getOrderRequest();
            OrderRequest rhsOrderRequest;
            rhsOrderRequest = that.getOrderRequest();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderRequest", lhsOrderRequest), LocatorUtils.property(thatLocator, "orderRequest", rhsOrderRequest), lhsOrderRequest, rhsOrderRequest)) {
                return false;
            }
        }
        {
            MasterAgreementRequest lhsMasterAgreementRequest;
            lhsMasterAgreementRequest = this.getMasterAgreementRequest();
            MasterAgreementRequest rhsMasterAgreementRequest;
            rhsMasterAgreementRequest = that.getMasterAgreementRequest();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "masterAgreementRequest", lhsMasterAgreementRequest), LocatorUtils.property(thatLocator, "masterAgreementRequest", rhsMasterAgreementRequest), lhsMasterAgreementRequest, rhsMasterAgreementRequest)) {
                return false;
            }
        }
        {
            PunchOutSetupRequest lhsPunchOutSetupRequest;
            lhsPunchOutSetupRequest = this.getPunchOutSetupRequest();
            PunchOutSetupRequest rhsPunchOutSetupRequest;
            rhsPunchOutSetupRequest = that.getPunchOutSetupRequest();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "punchOutSetupRequest", lhsPunchOutSetupRequest), LocatorUtils.property(thatLocator, "punchOutSetupRequest", rhsPunchOutSetupRequest), lhsPunchOutSetupRequest, rhsPunchOutSetupRequest)) {
                return false;
            }
        }
        {
            ProviderSetupRequest lhsProviderSetupRequest;
            lhsProviderSetupRequest = this.getProviderSetupRequest();
            ProviderSetupRequest rhsProviderSetupRequest;
            rhsProviderSetupRequest = that.getProviderSetupRequest();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "providerSetupRequest", lhsProviderSetupRequest), LocatorUtils.property(thatLocator, "providerSetupRequest", rhsProviderSetupRequest), lhsProviderSetupRequest, rhsProviderSetupRequest)) {
                return false;
            }
        }
        {
            StatusUpdateRequest lhsStatusUpdateRequest;
            lhsStatusUpdateRequest = this.getStatusUpdateRequest();
            StatusUpdateRequest rhsStatusUpdateRequest;
            rhsStatusUpdateRequest = that.getStatusUpdateRequest();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "statusUpdateRequest", lhsStatusUpdateRequest), LocatorUtils.property(thatLocator, "statusUpdateRequest", rhsStatusUpdateRequest), lhsStatusUpdateRequest, rhsStatusUpdateRequest)) {
                return false;
            }
        }
        {
            GetPendingRequest lhsGetPendingRequest;
            lhsGetPendingRequest = this.getGetPendingRequest();
            GetPendingRequest rhsGetPendingRequest;
            rhsGetPendingRequest = that.getGetPendingRequest();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "getPendingRequest", lhsGetPendingRequest), LocatorUtils.property(thatLocator, "getPendingRequest", rhsGetPendingRequest), lhsGetPendingRequest, rhsGetPendingRequest)) {
                return false;
            }
        }
        {
            SubscriptionListRequest lhsSubscriptionListRequest;
            lhsSubscriptionListRequest = this.getSubscriptionListRequest();
            SubscriptionListRequest rhsSubscriptionListRequest;
            rhsSubscriptionListRequest = that.getSubscriptionListRequest();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "subscriptionListRequest", lhsSubscriptionListRequest), LocatorUtils.property(thatLocator, "subscriptionListRequest", rhsSubscriptionListRequest), lhsSubscriptionListRequest, rhsSubscriptionListRequest)) {
                return false;
            }
        }
        {
            SubscriptionContentRequest lhsSubscriptionContentRequest;
            lhsSubscriptionContentRequest = this.getSubscriptionContentRequest();
            SubscriptionContentRequest rhsSubscriptionContentRequest;
            rhsSubscriptionContentRequest = that.getSubscriptionContentRequest();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "subscriptionContentRequest", lhsSubscriptionContentRequest), LocatorUtils.property(thatLocator, "subscriptionContentRequest", rhsSubscriptionContentRequest), lhsSubscriptionContentRequest, rhsSubscriptionContentRequest)) {
                return false;
            }
        }
        {
            SupplierListRequest lhsSupplierListRequest;
            lhsSupplierListRequest = this.getSupplierListRequest();
            SupplierListRequest rhsSupplierListRequest;
            rhsSupplierListRequest = that.getSupplierListRequest();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "supplierListRequest", lhsSupplierListRequest), LocatorUtils.property(thatLocator, "supplierListRequest", rhsSupplierListRequest), lhsSupplierListRequest, rhsSupplierListRequest)) {
                return false;
            }
        }
        {
            SupplierDataRequest lhsSupplierDataRequest;
            lhsSupplierDataRequest = this.getSupplierDataRequest();
            SupplierDataRequest rhsSupplierDataRequest;
            rhsSupplierDataRequest = that.getSupplierDataRequest();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "supplierDataRequest", lhsSupplierDataRequest), LocatorUtils.property(thatLocator, "supplierDataRequest", rhsSupplierDataRequest), lhsSupplierDataRequest, rhsSupplierDataRequest)) {
                return false;
            }
        }
        {
            CopyRequest lhsCopyRequest;
            lhsCopyRequest = this.getCopyRequest();
            CopyRequest rhsCopyRequest;
            rhsCopyRequest = that.getCopyRequest();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "copyRequest", lhsCopyRequest), LocatorUtils.property(thatLocator, "copyRequest", rhsCopyRequest), lhsCopyRequest, rhsCopyRequest)) {
                return false;
            }
        }
        {
            CatalogUploadRequest lhsCatalogUploadRequest;
            lhsCatalogUploadRequest = this.getCatalogUploadRequest();
            CatalogUploadRequest rhsCatalogUploadRequest;
            rhsCatalogUploadRequest = that.getCatalogUploadRequest();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "catalogUploadRequest", lhsCatalogUploadRequest), LocatorUtils.property(thatLocator, "catalogUploadRequest", rhsCatalogUploadRequest), lhsCatalogUploadRequest, rhsCatalogUploadRequest)) {
                return false;
            }
        }
        {
            String lhsDeploymentMode;
            lhsDeploymentMode = this.getDeploymentMode();
            String rhsDeploymentMode;
            rhsDeploymentMode = that.getDeploymentMode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "deploymentMode", lhsDeploymentMode), LocatorUtils.property(thatLocator, "deploymentMode", rhsDeploymentMode), lhsDeploymentMode, rhsDeploymentMode)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            ProfileRequest theProfileRequest;
            theProfileRequest = this.getProfileRequest();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "profileRequest", theProfileRequest), currentHashCode, theProfileRequest);
        }
        {
            OrderRequest theOrderRequest;
            theOrderRequest = this.getOrderRequest();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderRequest", theOrderRequest), currentHashCode, theOrderRequest);
        }
        {
            MasterAgreementRequest theMasterAgreementRequest;
            theMasterAgreementRequest = this.getMasterAgreementRequest();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "masterAgreementRequest", theMasterAgreementRequest), currentHashCode, theMasterAgreementRequest);
        }
        {
            PunchOutSetupRequest thePunchOutSetupRequest;
            thePunchOutSetupRequest = this.getPunchOutSetupRequest();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "punchOutSetupRequest", thePunchOutSetupRequest), currentHashCode, thePunchOutSetupRequest);
        }
        {
            ProviderSetupRequest theProviderSetupRequest;
            theProviderSetupRequest = this.getProviderSetupRequest();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "providerSetupRequest", theProviderSetupRequest), currentHashCode, theProviderSetupRequest);
        }
        {
            StatusUpdateRequest theStatusUpdateRequest;
            theStatusUpdateRequest = this.getStatusUpdateRequest();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "statusUpdateRequest", theStatusUpdateRequest), currentHashCode, theStatusUpdateRequest);
        }
        {
            GetPendingRequest theGetPendingRequest;
            theGetPendingRequest = this.getGetPendingRequest();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "getPendingRequest", theGetPendingRequest), currentHashCode, theGetPendingRequest);
        }
        {
            SubscriptionListRequest theSubscriptionListRequest;
            theSubscriptionListRequest = this.getSubscriptionListRequest();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "subscriptionListRequest", theSubscriptionListRequest), currentHashCode, theSubscriptionListRequest);
        }
        {
            SubscriptionContentRequest theSubscriptionContentRequest;
            theSubscriptionContentRequest = this.getSubscriptionContentRequest();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "subscriptionContentRequest", theSubscriptionContentRequest), currentHashCode, theSubscriptionContentRequest);
        }
        {
            SupplierListRequest theSupplierListRequest;
            theSupplierListRequest = this.getSupplierListRequest();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "supplierListRequest", theSupplierListRequest), currentHashCode, theSupplierListRequest);
        }
        {
            SupplierDataRequest theSupplierDataRequest;
            theSupplierDataRequest = this.getSupplierDataRequest();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "supplierDataRequest", theSupplierDataRequest), currentHashCode, theSupplierDataRequest);
        }
        {
            CopyRequest theCopyRequest;
            theCopyRequest = this.getCopyRequest();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "copyRequest", theCopyRequest), currentHashCode, theCopyRequest);
        }
        {
            CatalogUploadRequest theCatalogUploadRequest;
            theCatalogUploadRequest = this.getCatalogUploadRequest();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "catalogUploadRequest", theCatalogUploadRequest), currentHashCode, theCatalogUploadRequest);
        }
        {
            String theDeploymentMode;
            theDeploymentMode = this.getDeploymentMode();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "deploymentMode", theDeploymentMode), currentHashCode, theDeploymentMode);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
