//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 10:13:20 AM EDT 
//


package com.unilog.punchout.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Status"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;choice>
 *             &lt;element ref="{}ProfileResponse"/>
 *             &lt;element ref="{}PunchOutSetupResponse"/>
 *             &lt;element ref="{}ProviderSetupResponse"/>
 *             &lt;element ref="{}GetPendingResponse"/>
 *             &lt;element ref="{}SubscriptionListResponse"/>
 *             &lt;element ref="{}SubscriptionContentResponse"/>
 *             &lt;element ref="{}SupplierListResponse"/>
 *             &lt;element ref="{}SupplierDataResponse"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "status",
    "profileResponse",
    "punchOutSetupResponse",
    "providerSetupResponse",
    "getPendingResponse",
    "subscriptionListResponse",
    "subscriptionContentResponse",
    "supplierListResponse",
    "supplierDataResponse"
})
@XmlRootElement(name = "Response")
public class Response
    implements Serializable, Equals, HashCode, ToString
{

    @XmlElement(name = "Status", required = true)
    protected Status status;
    @XmlElement(name = "ProfileResponse")
    protected ProfileResponse profileResponse;
    @XmlElement(name = "PunchOutSetupResponse")
    protected PunchOutSetupResponse punchOutSetupResponse;
    @XmlElement(name = "ProviderSetupResponse")
    protected ProviderSetupResponse providerSetupResponse;
    @XmlElement(name = "GetPendingResponse")
    protected GetPendingResponse getPendingResponse;
    @XmlElement(name = "SubscriptionListResponse")
    protected SubscriptionListResponse subscriptionListResponse;
    @XmlElement(name = "SubscriptionContentResponse")
    protected SubscriptionContentResponse subscriptionContentResponse;
    @XmlElement(name = "SupplierListResponse")
    protected SupplierListResponse supplierListResponse;
    @XmlElement(name = "SupplierDataResponse")
    protected SupplierDataResponse supplierDataResponse;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the profileResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ProfileResponse }
     *     
     */
    public ProfileResponse getProfileResponse() {
        return profileResponse;
    }

    /**
     * Sets the value of the profileResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProfileResponse }
     *     
     */
    public void setProfileResponse(ProfileResponse value) {
        this.profileResponse = value;
    }

    /**
     * Gets the value of the punchOutSetupResponse property.
     * 
     * @return
     *     possible object is
     *     {@link PunchOutSetupResponse }
     *     
     */
    public PunchOutSetupResponse getPunchOutSetupResponse() {
        return punchOutSetupResponse;
    }

    /**
     * Sets the value of the punchOutSetupResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link PunchOutSetupResponse }
     *     
     */
    public void setPunchOutSetupResponse(PunchOutSetupResponse value) {
        this.punchOutSetupResponse = value;
    }

    /**
     * Gets the value of the providerSetupResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ProviderSetupResponse }
     *     
     */
    public ProviderSetupResponse getProviderSetupResponse() {
        return providerSetupResponse;
    }

    /**
     * Sets the value of the providerSetupResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProviderSetupResponse }
     *     
     */
    public void setProviderSetupResponse(ProviderSetupResponse value) {
        this.providerSetupResponse = value;
    }

    /**
     * Gets the value of the getPendingResponse property.
     * 
     * @return
     *     possible object is
     *     {@link GetPendingResponse }
     *     
     */
    public GetPendingResponse getGetPendingResponse() {
        return getPendingResponse;
    }

    /**
     * Sets the value of the getPendingResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetPendingResponse }
     *     
     */
    public void setGetPendingResponse(GetPendingResponse value) {
        this.getPendingResponse = value;
    }

    /**
     * Gets the value of the subscriptionListResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriptionListResponse }
     *     
     */
    public SubscriptionListResponse getSubscriptionListResponse() {
        return subscriptionListResponse;
    }

    /**
     * Sets the value of the subscriptionListResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriptionListResponse }
     *     
     */
    public void setSubscriptionListResponse(SubscriptionListResponse value) {
        this.subscriptionListResponse = value;
    }

    /**
     * Gets the value of the subscriptionContentResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriptionContentResponse }
     *     
     */
    public SubscriptionContentResponse getSubscriptionContentResponse() {
        return subscriptionContentResponse;
    }

    /**
     * Sets the value of the subscriptionContentResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriptionContentResponse }
     *     
     */
    public void setSubscriptionContentResponse(SubscriptionContentResponse value) {
        this.subscriptionContentResponse = value;
    }

    /**
     * Gets the value of the supplierListResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierListResponse }
     *     
     */
    public SupplierListResponse getSupplierListResponse() {
        return supplierListResponse;
    }

    /**
     * Sets the value of the supplierListResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierListResponse }
     *     
     */
    public void setSupplierListResponse(SupplierListResponse value) {
        this.supplierListResponse = value;
    }

    /**
     * Gets the value of the supplierDataResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierDataResponse }
     *     
     */
    public SupplierDataResponse getSupplierDataResponse() {
        return supplierDataResponse;
    }

    /**
     * Sets the value of the supplierDataResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierDataResponse }
     *     
     */
    public void setSupplierDataResponse(SupplierDataResponse value) {
        this.supplierDataResponse = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            Status theStatus;
            theStatus = this.getStatus();
            strategy.appendField(locator, this, "status", buffer, theStatus);
        }
        {
            ProfileResponse theProfileResponse;
            theProfileResponse = this.getProfileResponse();
            strategy.appendField(locator, this, "profileResponse", buffer, theProfileResponse);
        }
        {
            PunchOutSetupResponse thePunchOutSetupResponse;
            thePunchOutSetupResponse = this.getPunchOutSetupResponse();
            strategy.appendField(locator, this, "punchOutSetupResponse", buffer, thePunchOutSetupResponse);
        }
        {
            ProviderSetupResponse theProviderSetupResponse;
            theProviderSetupResponse = this.getProviderSetupResponse();
            strategy.appendField(locator, this, "providerSetupResponse", buffer, theProviderSetupResponse);
        }
        {
            GetPendingResponse theGetPendingResponse;
            theGetPendingResponse = this.getGetPendingResponse();
            strategy.appendField(locator, this, "getPendingResponse", buffer, theGetPendingResponse);
        }
        {
            SubscriptionListResponse theSubscriptionListResponse;
            theSubscriptionListResponse = this.getSubscriptionListResponse();
            strategy.appendField(locator, this, "subscriptionListResponse", buffer, theSubscriptionListResponse);
        }
        {
            SubscriptionContentResponse theSubscriptionContentResponse;
            theSubscriptionContentResponse = this.getSubscriptionContentResponse();
            strategy.appendField(locator, this, "subscriptionContentResponse", buffer, theSubscriptionContentResponse);
        }
        {
            SupplierListResponse theSupplierListResponse;
            theSupplierListResponse = this.getSupplierListResponse();
            strategy.appendField(locator, this, "supplierListResponse", buffer, theSupplierListResponse);
        }
        {
            SupplierDataResponse theSupplierDataResponse;
            theSupplierDataResponse = this.getSupplierDataResponse();
            strategy.appendField(locator, this, "supplierDataResponse", buffer, theSupplierDataResponse);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Response)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Response that = ((Response) object);
        {
            Status lhsStatus;
            lhsStatus = this.getStatus();
            Status rhsStatus;
            rhsStatus = that.getStatus();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "status", lhsStatus), LocatorUtils.property(thatLocator, "status", rhsStatus), lhsStatus, rhsStatus)) {
                return false;
            }
        }
        {
            ProfileResponse lhsProfileResponse;
            lhsProfileResponse = this.getProfileResponse();
            ProfileResponse rhsProfileResponse;
            rhsProfileResponse = that.getProfileResponse();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "profileResponse", lhsProfileResponse), LocatorUtils.property(thatLocator, "profileResponse", rhsProfileResponse), lhsProfileResponse, rhsProfileResponse)) {
                return false;
            }
        }
        {
            PunchOutSetupResponse lhsPunchOutSetupResponse;
            lhsPunchOutSetupResponse = this.getPunchOutSetupResponse();
            PunchOutSetupResponse rhsPunchOutSetupResponse;
            rhsPunchOutSetupResponse = that.getPunchOutSetupResponse();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "punchOutSetupResponse", lhsPunchOutSetupResponse), LocatorUtils.property(thatLocator, "punchOutSetupResponse", rhsPunchOutSetupResponse), lhsPunchOutSetupResponse, rhsPunchOutSetupResponse)) {
                return false;
            }
        }
        {
            ProviderSetupResponse lhsProviderSetupResponse;
            lhsProviderSetupResponse = this.getProviderSetupResponse();
            ProviderSetupResponse rhsProviderSetupResponse;
            rhsProviderSetupResponse = that.getProviderSetupResponse();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "providerSetupResponse", lhsProviderSetupResponse), LocatorUtils.property(thatLocator, "providerSetupResponse", rhsProviderSetupResponse), lhsProviderSetupResponse, rhsProviderSetupResponse)) {
                return false;
            }
        }
        {
            GetPendingResponse lhsGetPendingResponse;
            lhsGetPendingResponse = this.getGetPendingResponse();
            GetPendingResponse rhsGetPendingResponse;
            rhsGetPendingResponse = that.getGetPendingResponse();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "getPendingResponse", lhsGetPendingResponse), LocatorUtils.property(thatLocator, "getPendingResponse", rhsGetPendingResponse), lhsGetPendingResponse, rhsGetPendingResponse)) {
                return false;
            }
        }
        {
            SubscriptionListResponse lhsSubscriptionListResponse;
            lhsSubscriptionListResponse = this.getSubscriptionListResponse();
            SubscriptionListResponse rhsSubscriptionListResponse;
            rhsSubscriptionListResponse = that.getSubscriptionListResponse();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "subscriptionListResponse", lhsSubscriptionListResponse), LocatorUtils.property(thatLocator, "subscriptionListResponse", rhsSubscriptionListResponse), lhsSubscriptionListResponse, rhsSubscriptionListResponse)) {
                return false;
            }
        }
        {
            SubscriptionContentResponse lhsSubscriptionContentResponse;
            lhsSubscriptionContentResponse = this.getSubscriptionContentResponse();
            SubscriptionContentResponse rhsSubscriptionContentResponse;
            rhsSubscriptionContentResponse = that.getSubscriptionContentResponse();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "subscriptionContentResponse", lhsSubscriptionContentResponse), LocatorUtils.property(thatLocator, "subscriptionContentResponse", rhsSubscriptionContentResponse), lhsSubscriptionContentResponse, rhsSubscriptionContentResponse)) {
                return false;
            }
        }
        {
            SupplierListResponse lhsSupplierListResponse;
            lhsSupplierListResponse = this.getSupplierListResponse();
            SupplierListResponse rhsSupplierListResponse;
            rhsSupplierListResponse = that.getSupplierListResponse();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "supplierListResponse", lhsSupplierListResponse), LocatorUtils.property(thatLocator, "supplierListResponse", rhsSupplierListResponse), lhsSupplierListResponse, rhsSupplierListResponse)) {
                return false;
            }
        }
        {
            SupplierDataResponse lhsSupplierDataResponse;
            lhsSupplierDataResponse = this.getSupplierDataResponse();
            SupplierDataResponse rhsSupplierDataResponse;
            rhsSupplierDataResponse = that.getSupplierDataResponse();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "supplierDataResponse", lhsSupplierDataResponse), LocatorUtils.property(thatLocator, "supplierDataResponse", rhsSupplierDataResponse), lhsSupplierDataResponse, rhsSupplierDataResponse)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            Status theStatus;
            theStatus = this.getStatus();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "status", theStatus), currentHashCode, theStatus);
        }
        {
            ProfileResponse theProfileResponse;
            theProfileResponse = this.getProfileResponse();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "profileResponse", theProfileResponse), currentHashCode, theProfileResponse);
        }
        {
            PunchOutSetupResponse thePunchOutSetupResponse;
            thePunchOutSetupResponse = this.getPunchOutSetupResponse();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "punchOutSetupResponse", thePunchOutSetupResponse), currentHashCode, thePunchOutSetupResponse);
        }
        {
            ProviderSetupResponse theProviderSetupResponse;
            theProviderSetupResponse = this.getProviderSetupResponse();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "providerSetupResponse", theProviderSetupResponse), currentHashCode, theProviderSetupResponse);
        }
        {
            GetPendingResponse theGetPendingResponse;
            theGetPendingResponse = this.getGetPendingResponse();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "getPendingResponse", theGetPendingResponse), currentHashCode, theGetPendingResponse);
        }
        {
            SubscriptionListResponse theSubscriptionListResponse;
            theSubscriptionListResponse = this.getSubscriptionListResponse();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "subscriptionListResponse", theSubscriptionListResponse), currentHashCode, theSubscriptionListResponse);
        }
        {
            SubscriptionContentResponse theSubscriptionContentResponse;
            theSubscriptionContentResponse = this.getSubscriptionContentResponse();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "subscriptionContentResponse", theSubscriptionContentResponse), currentHashCode, theSubscriptionContentResponse);
        }
        {
            SupplierListResponse theSupplierListResponse;
            theSupplierListResponse = this.getSupplierListResponse();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "supplierListResponse", theSupplierListResponse), currentHashCode, theSupplierListResponse);
        }
        {
            SupplierDataResponse theSupplierDataResponse;
            theSupplierDataResponse = this.getSupplierDataResponse();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "supplierDataResponse", theSupplierDataResponse), currentHashCode, theSupplierDataResponse);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
