//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 10:13:20 AM EDT 
//


package com.unilog.punchout.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DocumentReference"/>
 *         &lt;element ref="{}Status"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;choice>
 *             &lt;element ref="{}PaymentStatus"/>
 *             &lt;element ref="{}SourcingStatus"/>
 *             &lt;element ref="{}InvoiceStatus"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentReference",
    "status",
    "paymentStatus",
    "sourcingStatus",
    "invoiceStatus"
})
@XmlRootElement(name = "StatusUpdateRequest")
public class StatusUpdateRequest
    implements Serializable, Equals, HashCode, ToString
{

    @XmlElement(name = "DocumentReference", required = true)
    protected DocumentReference documentReference;
    @XmlElement(name = "Status", required = true)
    protected Status status;
    @XmlElement(name = "PaymentStatus")
    protected PaymentStatus paymentStatus;
    @XmlElement(name = "SourcingStatus")
    protected SourcingStatus sourcingStatus;
    @XmlElement(name = "InvoiceStatus")
    protected InvoiceStatus invoiceStatus;

    /**
     * Gets the value of the documentReference property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReference }
     *     
     */
    public DocumentReference getDocumentReference() {
        return documentReference;
    }

    /**
     * Sets the value of the documentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReference }
     *     
     */
    public void setDocumentReference(DocumentReference value) {
        this.documentReference = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the paymentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentStatus }
     *     
     */
    public PaymentStatus getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * Sets the value of the paymentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentStatus }
     *     
     */
    public void setPaymentStatus(PaymentStatus value) {
        this.paymentStatus = value;
    }

    /**
     * Gets the value of the sourcingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link SourcingStatus }
     *     
     */
    public SourcingStatus getSourcingStatus() {
        return sourcingStatus;
    }

    /**
     * Sets the value of the sourcingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourcingStatus }
     *     
     */
    public void setSourcingStatus(SourcingStatus value) {
        this.sourcingStatus = value;
    }

    /**
     * Gets the value of the invoiceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceStatus }
     *     
     */
    public InvoiceStatus getInvoiceStatus() {
        return invoiceStatus;
    }

    /**
     * Sets the value of the invoiceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceStatus }
     *     
     */
    public void setInvoiceStatus(InvoiceStatus value) {
        this.invoiceStatus = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            DocumentReference theDocumentReference;
            theDocumentReference = this.getDocumentReference();
            strategy.appendField(locator, this, "documentReference", buffer, theDocumentReference);
        }
        {
            Status theStatus;
            theStatus = this.getStatus();
            strategy.appendField(locator, this, "status", buffer, theStatus);
        }
        {
            PaymentStatus thePaymentStatus;
            thePaymentStatus = this.getPaymentStatus();
            strategy.appendField(locator, this, "paymentStatus", buffer, thePaymentStatus);
        }
        {
            SourcingStatus theSourcingStatus;
            theSourcingStatus = this.getSourcingStatus();
            strategy.appendField(locator, this, "sourcingStatus", buffer, theSourcingStatus);
        }
        {
            InvoiceStatus theInvoiceStatus;
            theInvoiceStatus = this.getInvoiceStatus();
            strategy.appendField(locator, this, "invoiceStatus", buffer, theInvoiceStatus);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof StatusUpdateRequest)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final StatusUpdateRequest that = ((StatusUpdateRequest) object);
        {
            DocumentReference lhsDocumentReference;
            lhsDocumentReference = this.getDocumentReference();
            DocumentReference rhsDocumentReference;
            rhsDocumentReference = that.getDocumentReference();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "documentReference", lhsDocumentReference), LocatorUtils.property(thatLocator, "documentReference", rhsDocumentReference), lhsDocumentReference, rhsDocumentReference)) {
                return false;
            }
        }
        {
            Status lhsStatus;
            lhsStatus = this.getStatus();
            Status rhsStatus;
            rhsStatus = that.getStatus();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "status", lhsStatus), LocatorUtils.property(thatLocator, "status", rhsStatus), lhsStatus, rhsStatus)) {
                return false;
            }
        }
        {
            PaymentStatus lhsPaymentStatus;
            lhsPaymentStatus = this.getPaymentStatus();
            PaymentStatus rhsPaymentStatus;
            rhsPaymentStatus = that.getPaymentStatus();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "paymentStatus", lhsPaymentStatus), LocatorUtils.property(thatLocator, "paymentStatus", rhsPaymentStatus), lhsPaymentStatus, rhsPaymentStatus)) {
                return false;
            }
        }
        {
            SourcingStatus lhsSourcingStatus;
            lhsSourcingStatus = this.getSourcingStatus();
            SourcingStatus rhsSourcingStatus;
            rhsSourcingStatus = that.getSourcingStatus();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "sourcingStatus", lhsSourcingStatus), LocatorUtils.property(thatLocator, "sourcingStatus", rhsSourcingStatus), lhsSourcingStatus, rhsSourcingStatus)) {
                return false;
            }
        }
        {
            InvoiceStatus lhsInvoiceStatus;
            lhsInvoiceStatus = this.getInvoiceStatus();
            InvoiceStatus rhsInvoiceStatus;
            rhsInvoiceStatus = that.getInvoiceStatus();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "invoiceStatus", lhsInvoiceStatus), LocatorUtils.property(thatLocator, "invoiceStatus", rhsInvoiceStatus), lhsInvoiceStatus, rhsInvoiceStatus)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            DocumentReference theDocumentReference;
            theDocumentReference = this.getDocumentReference();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "documentReference", theDocumentReference), currentHashCode, theDocumentReference);
        }
        {
            Status theStatus;
            theStatus = this.getStatus();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "status", theStatus), currentHashCode, theStatus);
        }
        {
            PaymentStatus thePaymentStatus;
            thePaymentStatus = this.getPaymentStatus();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "paymentStatus", thePaymentStatus), currentHashCode, thePaymentStatus);
        }
        {
            SourcingStatus theSourcingStatus;
            theSourcingStatus = this.getSourcingStatus();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "sourcingStatus", theSourcingStatus), currentHashCode, theSourcingStatus);
        }
        {
            InvoiceStatus theInvoiceStatus;
            theInvoiceStatus = this.getInvoiceStatus();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "invoiceStatus", theInvoiceStatus), currentHashCode, theInvoiceStatus);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
