package com.unilog.velocitytool.contextkeyinterface;

public interface SocialMediaContextkey {
	final String CIMM2BCENTRAL_FINAL_REQUEST_URL="CIMM2BCENTRAL_FINAL_REQUEST_URL";
	final String CIMM2BCENTRAL_CONNECTION_URL="CIMM2BCENTRAL_CONNECTION_URL";
	final String CIMM2BCENTRAL_FACEBOOK_URL_SOURCE ="CIMM2BCENTRAL_FACEBOOK_URL_SOURCE";
	final String CIMM2BCENTRAL_TWITTER_URL_SOURCE ="CIMM2BCENTRAL_TWITTER_URL_SOURCE";
	final String CIMM2BCENTRAL_BLOG_URL_SOURCE = "CIMM2BCENTRAL_BLOG_URL_SOURCE";
	final String CIMM2BCENTRAL_BLOG_POST_DETAIL_URL_SOURCE = "CIMM2BCENTRAL_BLOG_POST_DETAIL_URL_SOURCE";
	final String CIMM2BCENTRAL_BLOG_FEED_URL = "CIMM2BCENTRAL_BLOG_FEED_URL";
	final String CIMM2BCENTRAL_CASE_STUDIES_FEED_URL = "CIMM2BCENTRAL_CASE_STUDIES_FEED_URL";
	final String CIMM2BCENTRAL_PRODUCT_ARTICLE_FEED_URL = "CIMM2BCENTRAL_PRODUCT_ARTICLE_FEED_URL";
	final String CIMM2BCENTRAL_CLIENT_ID ="Clientid";
	
	final String SITE_ID ="SITE_ID";
	
	final String FACEBOOK_NUMBER_OF_POSTS ="FACEBOOK_NUMBER_OF_POSTS";
	final String TWITTER_NUMBER_OF_POSTS ="TWITTER_NUMBER_OF_POSTS";
	final String BLOG_NUMBER_OF_POSTS = "BLOG_NUMBER_OF_POSTS";

}
